### ISSUE TITLE
Error when used with importmaps on rails 7

### ISSUE THREAD

**Issue by AlexB52** [AlexB52/rails-playground#31]
This happens on a fairly simple rails 7 apps using importmaps and stimulus

<img width="1219" alt="CleanShot 2023-11-09 at 17 39 45@2x" src="https://github.com/AlexB52/rails-playground/assets/7149034/21ac7316-9281-49bd-9181-51d162912704">

**Comment by vitaly-andr** [comment]
Hello Alex
Did you find the solution?

**Comment by AlexB52** [comment]
Hi @vitaly-andr 
A fix should not be too hard, but I haven't gotten around to it. 
I don't have the opportunity to use this engine much at the moment. 
I'll try to look at it, but can't promise a timeframe. 
Some help would be appreciated if this is something you'd be keen to look at.

**Comment by AlexB52** [comment]
@vitaly-andr 
Updating the `rails-playground` gem to `0.1.6` should fix the issue. 
Let me know how it goes
